import warrior from '../assets/images/spirit-images/wasteland/Fainting Warrior.png'
import refugee from '../assets/images/spirit-images/wasteland/Frightened Refugee.png'
import soldier from '../assets/images/spirit-images/wasteland/Courageous Soldier.png'
import survivor from '../assets/images/spirit-images/wasteland/Stealthy Survivor.png'
import captain from '../assets/images/spirit-images/wasteland/Saluting Captain.png'
import scout from '../assets/images/spirit-images/wasteland/Lookout Scout.png'
import protector from '../assets/images/spirit-images/wasteland/Saluting Protector.png'
import parent from '../assets/images/spirit-images/wasteland/Pleaful Parent.png'
import pianist from '../assets/images/spirit-images/wasteland/Respectful Pianist.png'
import whisperer from '../assets/images/spirit-images/wasteland/Crab Whisperer.png'
import carpenter from '../assets/images/spirit-images/wasteland/Snoozing Carpenter.png'
import muralist from '../assets/images/spirit-images/wasteland/Nodding Muralist.png'
import walker from '../assets/images/spirit-images/wasteland/Crab Walker.png'
import herbalist from '../assets/images/spirit-images/wasteland/Playfighting Herbalist.png'
import farmer from '../assets/images/spirit-images/wasteland/Scarecrow Farmer.png'
import alchemist from '../assets/images/spirit-images/wasteland/Indifferent Alchemist.png'
import commodore from '../assets/images/spirit-images/wasteland/Ceasing Commodore.png'
import angler from '../assets/images/spirit-images/wasteland/Anxious Angler.png'
import boatswain from '../assets/images/spirit-images/wasteland/Bumbling Boatswain.png'
import cackling from '../assets/images/spirit-images/wasteland/Cackling Cannoneer.png'

export const WASTELAND_SPIRIT_1 = warrior
export const WASTELAND_SPIRIT_2 = refugee
export const WASTELAND_SPIRIT_3 = soldier
export const WASTELAND_SPIRIT_4 = survivor
export const WASTELAND_SPIRIT_5 = captain
export const WASTELAND_SPIRIT_6 = scout

export const WASTELAND_SEASON_SPIRIT_1 = protector
export const WASTELAND_SEASON_SPIRIT_2 = parent
export const WASTELAND_SEASON_SPIRIT_3 = pianist
export const WASTELAND_SEASON_SPIRIT_4 = whisperer
export const WASTELAND_SEASON_SPIRIT_5 = carpenter
export const WASTELAND_SEASON_SPIRIT_6 = muralist
export const WASTELAND_SEASON_SPIRIT_7 = walker
export const WASTELAND_SEASON_SPIRIT_8 = herbalist
export const WASTELAND_SEASON_SPIRIT_9 = farmer
export const WASTELAND_SEASON_SPIRIT_10 = alchemist
export const WASTELAND_SEASON_SPIRIT_11 = commodore
export const WASTELAND_SEASON_SPIRIT_12 = angler
export const WASTELAND_SEASON_SPIRIT_13 = boatswain
export const WASTELAND_SEASON_SPIRIT_14 = cackling
